# -*- coding: utf-8 -*-
"""blockchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ir-BsL6LVVMCcaEv07YUeNHNiUw16wGl
"""

import requests
import pandas as pd

def fetch_crypto_data():
    url = "https://api.coingecko.com/api/v3/coins/markets"
    params = {
        "vs_currency": "usd",
        "order": "market_cap_desc",
        "per_page": 50,
        "page": 1,
    }
    response = requests.get(url, params=params)
    data = response.json()
    df = pd.DataFrame(data)[["name", "symbol", "current_price", "market_cap", "total_volume", "price_change_percentage_24h"]]
    return df

from google.colab import drive
drive.mount('/content/drive')

def analyze_crypto_data(df):
    top_5_by_market_cap = df.nlargest(5, "market_cap")
    avg_price = df["current_price"].mean()
    highest_change = df["price_change_percentage_24h"].max()
    lowest_change = df["price_change_percentage_24h"].min()

    return {
        "top_5_by_market_cap": top_5_by_market_cap,
        "avg_price": avg_price,
        "highest_change": highest_change,
        "lowest_change": lowest_change,
    }

import pandas as pd
import time

def update_excel(df, filename="crypto_data.xlsx"):
    with pd.ExcelWriter(filename, engine="openpyxl", mode="w") as writer:
        df.to_excel(writer, index=False, sheet_name="Sheet1")

# Run updates every 5 minutes
while True:
    df = fetch_crypto_data()
    update_excel(df)
    print("Excel file updated.")
    time.sleep(300)  # 300 seconds = 5 minutes